
services:
  nginx:
    image: nginx:alpine
    ports:
      - "9000:80"
    volumes:
      - ../Nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user-service
      - product-service
      - order-service
    networks:
      - ecom-network

  # --- MICROSERVICES ---
  user-service:
    build:
      context: ../Services/user-service
    environment:
      DB_HOST: user-db
      DB_USER: ecom_user
      DB_PASSWORD_FILE: /run/secrets/postgres_password
      JWT_SECRET_FILE: /run/secrets/jwt_secret
    secrets:
      - postgres_password
      - jwt_secret
    depends_on:
      - user-db
    networks:
      - ecom-network

  product-service:
    build:
      context: ../Services/product-service
    environment:
      DB_HOST: product-db
      DB_USER: ecom_user
      DB_PASSWORD_FILE: /run/secrets/postgres_password
      REDIS_HOST: redis
      REDIS_PASSWORD_FILE: /run/secrets/redis_password
      JWT_SECRET_FILE: /run/secrets/jwt_secret
    secrets:
      - postgres_password
      - redis_password
      - jwt_secret
    depends_on:
      - product-db
      - redis
    networks:
      - ecom-network

  order-service:
    build:
      context: ../Services/order-service
    environment:
      DB_HOST: order-db
      DB_USER: ecom_user
      DB_PASSWORD_FILE: /run/secrets/postgres_password
      JWT_SECRET_FILE: /run/secrets/jwt_secret
    secrets:
      - postgres_password
      - jwt_secret
    depends_on:
      - order-db
    networks:
      - ecom-network

  # --- REDIS CACHE ---
  redis:
    build:
      context: ../Redis
    secrets:
      - redis_password
    networks:
      - ecom-network

  # --- POSTGRES DATABASES ---
  user-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ecom_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: user_db
    secrets:
      - postgres_password
    networks:
      - ecom-network

  product-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ecom_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: product_db
    secrets:
      - postgres_password
    networks:
      - ecom-network

  order-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ecom_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: order_db
    secrets:
      - postgres_password
    networks:
      - ecom-network

networks:
  ecom-network:
    driver: bridge

secrets:
  jwt_secret:
    file: ../secrets/jwt_secret.txt
  postgres_password:
    file: ../secrets/postgres_password.txt
  redis_password:
    file: ../secrets/redis_password.txt