events { worker_connections 1024; }

http {
    server {
        listen 80;

        location /api/users {
            proxy_pass http://user-service:5001; 
        }

        location /api/products {
            proxy_pass http://product-service:5002;
        }

        location /api/orders {
            proxy_pass http://order-service:5003;
        }
    }
}